name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
    pull_request:
      branches:
        - 'master'
    paths-ignore:
        - '**/README.md'

env:
  REGISTRY: ghcr.io
  NODE_IMAGE_NAME: ${{ github.repository_owner }}/massa-node
  CLIENT_IMAGE_NAME: ${{ github.repository_owner }}/massa-client

jobs:

  pre-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.0.0
      with:
        dockerfile: Dockerfile

  massa-node:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: docker_metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.NODE_IMAGE_NAME }}

    - name: Build Massa node Docker image
      id: massa_node_build_docker_image
      uses: docker/build-push-action@v3
      with:
        load: true
        target: massa-node
        tags: ${{ env.NODE_IMAGE_NAME }}

    - name: Test built image using Container Structure Tests Massa node Docker image
      uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: ${{ env.NODE_IMAGE_NAME }}
        configFile: tests/node-config.yml

    - name: Analyze built image using Dive
      uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ env.NODE_IMAGE_NAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for image vulnerabilities using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.NODE_IMAGE_NAME }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL

    - name: Push Massa node Docker image
      id: massa_node_push_docker_image
      uses: docker/build-push-action@v3
      with:
        push: true
        target: massa-node
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}

  massa-client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: docker_metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.CLIENT_IMAGE_NAME }}

    - name: Build Massa client Docker image
      id: massa_client_build_docker_image
      uses: docker/build-push-action@v3
      with:
        load: true
        target: massa-client
        tags: ${{ env.CLIENT_IMAGE_NAME }}

    - name: Test built image using Container Structure Tests Massa client Docker image
      uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: ${{ env.CLIENT_IMAGE_NAME }}
        configFile: tests/client-config.yml

    - name: Analyze built image using Dive
      uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ env.CLIENT_IMAGE_NAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for image vulnerabilities using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.CLIENT_IMAGE_NAME }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL

    - name: Push Massa client Docker image
      id: massa_client_push_docker_image
      uses: docker/build-push-action@v3
      with:
        push: true
        target: massa-client
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
